services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    #ports:
      #- "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      - GF_SECURITY_COOKIE_SAMESITE=${GF_SECURITY_COOKIE_SAMESITE}
      - GF_SECURITY_COOKIE_SECURE=${GF_SECURITY_COOKIE_SECURE}
#      - GF_SERVER_ROOT_URL=http://localhost:3000/
    ports:
      - "${GF_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana

#  blackbox-exporter:
#    image: prom/blackbox-exporter:latest
#    container_name: blackbox-exporter
#    #ports:
#      #- "9115:9115"

  page_load_script:
    container_name: page_load_script
    build:
      context: ./page_mon
      dockerfile: Dockerfile
    volumes:
      - ./page_mon:/app
      - /tmp/selenium:/tmp
    #ports:
      #- "8015:8015"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - prometheus
    restart: on-failure:1

  webhook_proxy:
    container_name: webhook_proxy
    build:
      context: ./webhook_proxy
      dockerfile: Dockerfile
    #ports:
      #- "1234:1234"
    env_file:
      - .env
    restart: on-failure:1

volumes:
  grafana-data:
